name: gpw_alert_system

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stocks
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d stocks"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  data_fetcher:
    build: ./data_fetcher
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: stocks

  strategy_analyzer:
    build: ./strategy_analyzer
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: stocks

  alert_system:
    build: ./alert_system
    depends_on:
      strategy_analyzer:
        condition: service_started
    environment:
      EMAIL_HOST: smtp.example.com
      EMAIL_USER: user@example.com
      EMAIL_PASSWORD: password

  dashboard:
    build: ./dashboard
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
      strategy_analyzer:
        condition: service_started

  scheduler:
    build: ./scheduler
    depends_on:
      data_fetcher:
        condition: service_started
      strategy_analyzer:
        condition: service_started
    environment:
      REDIS_HOST: redis
    command: ["celery", "-A", "tasks", "worker"]

volumes:
  pgdata:
