FROM python:3.10

WORKDIR /app

# Kopiowanie pliku requirements.txt do kontenera
COPY requirements.txt /app/requirements.txt

# Instalacja zależności
RUN pip install --no-cache-dir -r /app/requirements.txt

# Kopiowanie pozostałych plików kodu aplikacji
COPY . /app/

CMD ["python", "main.py"]
